name:                experiment-autodocodec
version:             0.1.0.0
github:              "hallettj/experiment-autodocodec"
license:             BSD3
author:              "Jesse Hallett"
maintainer:          "jesse@sitr.us"
copyright:           "Copyright: (c) 2022 Jesse Hallett"

extra-source-files:
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/hallettj/experiment-autodocodec#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  - autodocodec
  - autodocodec-openapi3
  - insert-ordered-containers
  - lens
  - openapi3
  - scientific
  - text

executables:
  generate-openapi:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - experiment-autodocodec
    - aeson-pretty
    - bytestring

tests:
  experiment-autodocodec-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - experiment-autodocodec
    - aeson
    - autodocodec
    - hspec
    - text

ghc-options: -Wall
